// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 10:14:11 p. m.
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Fsoci/projects/portafolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/plugins/**/*.{js,ts,mjs}","C:/Users/Fsoci/projects/portafolio/composables/**/*.{js,ts,mjs}","C:/Users/Fsoci/projects/portafolio/utils/**/*.{js,ts,mjs}","C:/Users/Fsoci/projects/portafolio/pages/index.vue","C:/Users/Fsoci/projects/portafolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fsoci/projects/portafolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;